### ISSUE TITLE
Debian 报错

### ISSUE THREAD

**Issue by lem0nb** [bangbang93/minecraft-proxy#27]
Windows下config.yml是没有问题的
 错误信息：
/root/node_modules/prismarine-nbt/nbt.js:165
    const type = value[0]?.type ?? 'end'
                          ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/node_modules/minecraft-protocol/src/datatypes/minecraft.js:3:13)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/root/node_modules/minecraft-protocol/src/transforms/serializer.js:8:19)

Config.yml文件
https://github.com/lem0nb/somefiles/raw/main/config.yml

node -v
v10.24.0
npm -v
5.8.0

**Comment by bangbang93** [comment]
更新node版本，最低需要14.5
