### ISSUE TITLE
有没有之前版本的源码

### ISSUE THREAD

**Issue by Ligture** [bangbang93/minecraft-proxy#45]
9天前那个源码更新之后我编译出来运行就报错了 之前我编译过是正常的 我试了几个node版本都不行 并且在linux和windows下都试了不行
顺便发下报错的日志
TypeError: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.dirname (node:path:654:5)
    at Object.read (C:\jiasu\node_modules\src\read.ts:12:20)
    at loadConfig (C:\jiasu\src\config.ts:61:21)
    at main (C:\jiasu\bin\mcproxy:14:24)
    at Object.<anonymous> (C:\jiasu\bin\mcproxy:73:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by bangbang93** [comment]
release里有
而且你猜猜git是用来干什么的

**Comment by Ligture** [comment]
好我已经找到了
