### ISSUE TITLE
docker 无法启动

### ISSUE THREAD

**Issue by CornWorld** [bangbang93/minecraft-proxy#47]
logs:
```
# docker run -p 25565:25565 -v /root/config:/opt/minecraft-proxy/config bangbang93/minecraft-proxy
TypeError: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.dirname (node:path:1276:5)
    at Object.read (/opt/minecraft-proxy/node_modules/src/read.ts:12:20)
    at loadConfig (/opt/minecraft-proxy/src/config.ts:61:21)
    at main (/opt/minecraft-proxy/bin/mcproxy:14:24)
    at Object.<anonymous> (/opt/minecraft-proxy/bin/mcproxy:73:1)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'ERR_INVALID_ARG_TYPE'
}
```
env:
```
Docker version 20.10.5, build 55c4c88

Linux VM-20-16-centos 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by bangbang93** [comment]
Fixed in 9fe76a2e
