### ISSUE TITLE
编译安装启动报错

### ISSUE THREAD

**Issue by ours1505** [bangbang93/minecraft-proxy#48]
root@hyp:~/minecraft-proxy# ./bin/mcproxy 
Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (node:fs:727:3)
    at tryReadSync (node:fs:433:20)
    at Object.readFileSync (node:fs:479:19)
    at Object.read (/root/minecraft-proxy/node_modules/src/read.ts:13:18)
    at loadConfig (/root/minecraft-proxy/src/config.ts:61:21)
    at main (/root/minecraft-proxy/bin/mcproxy:14:24)
    at Object.<anonymous> (/root/minecraft-proxy/bin/mcproxy:73:1)
    at Module._compile (node:internal/modules/cjs/loader:1099:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -21,
  syscall: 'read',
  code: 'EISDIR'
}

**Comment by ours1505** [comment]
@bangbang93 给个解决方案啊

**Comment by bangbang93** [comment]
修了，更新代码就行

**Comment by ours1505** [comment]
> 修了，更新代码就行

谢谢 没看到 麻烦了 @bangbang93
