### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Ligture** [bangbang93/minecraft-proxy#54]
执行npm ci编译报错Cannot read properties of null (reading ‘pickAlgorithm‘)
github上下载的原生的一个没改
我怀疑是nodejs版本问题,能说下你是什么版本的吗

**Comment by bangbang93** [comment]
https://github.com/npm/cli/issues/3374
node>=14和npm>=6应当都是支持的

**Comment by Ligture** [comment]
编译出来了但是出新问题了

{"name":"master","hostname":"VM31762","pid":213409,"level":30,"msg":"all workers started","time":"2022-07-06T04:29:48.085Z","v":0}
{"name":"server","port":25566,"host":"0.0.0.0","worker":1,"hostname":"VM31762","pid":213418,"level":30,"msg":"ready","time":"2022-07-06T04:29:49.392Z","v":0}

/usr/proxy/minecraft-proxy-master/node_modules/ip-cidr/index.js:58
        address = new this.ipAddressType(address);
                  ^
TypeError: this.ipAddressType is not a constructor
    at IPCIDR.contains (/usr/proxy/minecraft-proxy-master/node_modules/ip-cidr/index.js:58:19)
    at /usr/proxy/minecraft-proxy-master/src/proxy-server.ts:121:58
    at Array.some (<anonymous>)
    at ProxyServer.isIpBanned (/usr/proxy/minecraft-proxy-master/src/proxy-server.ts:121:38)
    at ProxyServer.onConnection (/usr/proxy/minecraft-proxy-master/src/proxy-server.ts:71:14)
    at Server.<anonymous> (/usr/proxy/minecraft-proxy-master/src/proxy-server.ts:46:52)
    at Server.emit (node:events:520:28)
    at Object.onconnection (node:net:1573:8)
    at onconnection (node:internal/cluster/child:212:12)
    at Worker.onmessage (node:internal/cluster/child:55:7)
    at process.onInternalMessage (node:internal/cluster/utils:49:5)
    at process.emit (node:events:532:35)
    at process.emit (/usr/proxy/minecraft-proxy-master/node_modules/source-map-support/source-map-support.js:516:21)
    at emit (node:internal/child_process:938:14)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)

**Comment by bangbang93** [comment]
`npm ls ip-cidr`看下你这个包的版本
以及你安装时使用的是`npm i`还是`npm ci`
推荐使用`npm ci`以保证正确安装依赖版本

**Comment by Ligture** [comment]
2.1.5 用的npm ci

**Comment by bangbang93** [comment]
npm ci不应该会安装这个版本啊

**Comment by Ligture** [comment]
正常是哪个版本能指定安装吗

**Comment by bangbang93** [comment]
lock里写的是2.0.6，要不你发一下完整安装日志看看？
