### ISSUE TITLE
貌似没有认到版本

### ISSUE THREAD

**Issue by mocksonline** [bangbang93/minecraft-proxy#58]
{"name":"server","port":11051,"host":"0.0.0.0","worker":1,"hostname":"10_0_8_8","pid":8012,"level":50,"err":{"message":"Cannot read properties of undefined (reading 'minecraftVersion')","name":"TypeError","stack":"TypeError: Cannot read properties of undefined (reading 'minecraftVersion')\n    at MinecraftData.protocolVersionToMcVersion (C:\\snapshot\\minecraft-proxy\\dist\\minecraft-data.js:24:24)\n    at Client.awaitHandshake (C:\\snapshot\\minecraft-proxy\\dist\\client.js:66:61)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at ProxyServer.onConnection (C:\\snapshot\\minecraft-proxy\\dist\\proxy-server.js:76:31)"},"msg":"Cannot read properties of undefined (reading 'minecraftVersion')","time":"2022-07-27T15:02:28.565Z","v":0}

**Comment by mocksonline** [comment]
proxy:
  port: 11051 #监听端口
  host: 0.0.0.0 #监听ip
  workers: 0 #worker数量，以便充分利用多核服务器，0代表用上全部核心
defaultServer: ***** #默认服务器，若不想指定，则删除此行
servers:
  - serverName: ***** #服务连接的主机名
    proxyHost: *****# 后端服务实际ip
    proxyPort: 11051 #后端服务实际端口
    version: 1.19 #版本
    handlePing: false #是否接管ping响应
    onlineMode: true
    ping: #接管ping时必填
      maxPlayer: 100 #最大玩家
      description: motd #motd
      favicon: data:image/png;base64, #没有就不用设置
blockList:
  ips: #同时会阻拦掉ping请求
    - 114.114.114.114
    - 10.0.0.0/32
  usernames:
    - BadGays
  uuids: # 只有开了正版验证的服务端可以封禁uuid，离线服务器只能用usernames
    - 12b8b9e0eba0ca37e935f037ff1ae90d
profileEndpoint: https://api.mojang.com/profiles/minecraft
